### ISSUE TITLE
UTF-8 compatibility

### ISSUE THREAD

**Issue by eulores** [pacha/cels#6]
Your cels application/library is really amazing, well done!
Just a minor detail: please make it able to process UTF-8 encoded files.

Might be as simple as adding `encoding='UTF-8'` to each `read_text()` and `write_text()` function.

See this article for an example: [How can pathlib read_text() method display German Umlaute correctly?](https://stackoverflow.com/questions/71323243/how-can-pathlib-read-text-method-display-german-umlaute-correctly-on-windows-1)

I'm currently getting an exception:
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 761: character maps to <undefined>`

**Comment by pacha** [comment]
Hi @eulores, thanks! Happy to know that is useful. The problem should be solved in the latest version already (0.1.4).

ps. apart from explicitly indicating the `utf-8` encoding in the read operations, it was necessary to explicitly tell the YAML and JSON serializers [to use non-ascii characters](https://github.com/pacha/cels/commit/16718b7b79b8f47f61d74e591d0dffeb315de737#diff-0a3489b9dac18b4484c2aa96e24e480c4c69eec3fa89e0428d100b0c32bc3183) , but other than that it was quite straightforward. Thanks for reporting the issue :)
